export enum MchgView {
  CHOOSING_QUESTION = "CHOOSING_QUESTION",
  ANSWERING_MAIN_QUESTION = "ANSWERING_MAIN_QUESTION",
  ANSWERING_SUB_QUESTION = "ANSWERING_SUB_QUESTION",
  SHOWING_SUB_QUESTION_ANSWER = "SHOWING_SUB_QUESTION_ANSWER",
  SHOWING_ROUND_RESULT = "SHOWING_ROUND_RESULT",
}
